- name: Install Playwright browsers
  run: npx playwright install --with-deps

- name: Create auth folder
  run: mkdir -p playwright/.auth

- name: Run auth setup
  run: npx playwright test tests/auth.setup.spec.js
  env:
    USERNAME: ${{ secrets.USERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}

- name: Run Playwright tests
  run: npx playwright test